version: 2.1

executors:
  sonar-executor:
    docker:
      - image: circleci/openjdk:11
    environment:
      SONAR_TOKEN: ${SONAR_TOKEN}
      SONAR_HOST_URL: "https://sonarcloud.io" 
jobs:
  build:
    executor: sonar-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
      - run:
          name: Install Dependencies
          command: mvn install -DskipTests
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run:
          name: Run Tests
          command: mvn test

  sonar_scan:
    executor: sonar-executor
    steps:
      - checkout
      - run:
          name: Run SonarQube Scan
          command: |
            mvn sonar:sonar \
              -Dsonar.projectKey=your_project_key \
              -Dsonar.organization=your_organization_key \
              -Dsonar.host.url=$SONAR_HOST_URL \
              -Dsonar.login=$SONAR_TOKEN

workflows:
  version: 2
  build_and_analyze:
    jobs:
      - build
      - sonar_scan:
          requires:
            - build
