version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:14  
    working_directory: ~/app 

jobs:
  install_dependencies:
    executor: node-executor
    steps:
      - checkout  # Pulls down the latest code from your repository
      - restore_cache:
          keys:
            - v1-node-deps-{{ checksum "package-lock.json" }}  # Restore cached node_modules based on package-lock checksum
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-node-deps-{{ checksum "package-lock.json" }}  # Cache node_modules to speed up future builds

  lint_code:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-node-deps-{{ checksum "package-lock.json" }}
      - run:
          name: Run Linting
          command: npm run lint  

  run_tests:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-node-deps-{{ checksum "package-lock.json" }}
      - run:
          name: Run Tests
          command: npm test 

workflows:
  version: 2
  test_pipeline:
    jobs:
      - install_dependencies
      - lint_code:
          requires:
            - install_dependencies
      - run_tests:
          requires:
            - install_dependencies
